const assert = require('node:assert/strict');
const test = require('node:test');

const {
  MANAGED_BLOCK_START,
  MANAGED_BLOCK_END,
  applyManagedBlock,
  buildManagedMcpBlock,
  stripDuplicateMcpEntries,
  extractManagedBlock
} = require('../src/sync-claude-all-to-codex');

test('applyManagedBlock removes duplicate MCP entries outside managed block', () => {
  // Simulate the exact scenario from the bug: manual entries exist before the managed block
  const existingConfig = [
    'model = "gpt-5.3-codex"',
    '',
    '[mcp_servers.chrome-devtools-mcp]',
    'type = "stdio"',
    'command = "npx"',
    'args = ["-y", "chrome-devtools-mcp@latest"]',
    '',
    '[mcp_servers.doubao-image-mcp]',
    'type = "stdio"',
    'command = "node"',
    'args = ["/path/to/index.js"]',
    '',
    '[mcp_servers.doubao-image-mcp.env]',
    'DOUBAO_API_KEY = "test-key"',
    '',
    MANAGED_BLOCK_START,
    '# Auto-generated by scripts/sync-claude-all-to-codex.js',
    '# No managed MCP servers found from claude sources',
    MANAGED_BLOCK_END,
    ''
  ].join('\n');

  const newServers = {
    'chrome-devtools-mcp': { args: ['-y', 'chrome-devtools-mcp@latest'], command: 'npx' },
    'doubao-image-mcp': { args: ['/path/to/index.js'], command: 'node', env: { DOUBAO_API_KEY: 'test-key' } }
  };

  const { blockText } = buildManagedMcpBlock(newServers);
  const result = applyManagedBlock(existingConfig, blockText);

  // Count occurrences of each server header — should be exactly 1
  const chromeMatches = result.match(/\[mcp_servers\.chrome-devtools-mcp\]/g) || [];
  const doubaoMatches = result.match(/\[mcp_servers\.doubao-image-mcp\]/g) || [];
  const doubaoEnvMatches = result.match(/\[mcp_servers\.doubao-image-mcp\.env\]/g) || [];

  assert.equal(chromeMatches.length, 1, 'chrome-devtools-mcp should appear exactly once');
  assert.equal(doubaoMatches.length, 1, 'doubao-image-mcp should appear exactly once');
  assert.equal(doubaoEnvMatches.length, 0, 'doubao-image-mcp.env sub-table should be removed');

  // The model line should still be there
  assert.match(result, /model = "gpt-5\.3-codex"/);

  // The managed block markers should be present
  assert.match(result, new RegExp(MANAGED_BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.match(result, new RegExp(MANAGED_BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
});

test('applyManagedBlock preserves non-conflicting entries outside managed block', () => {
  const existingConfig = [
    'model = "gpt-5.3-codex"',
    '',
    '[mcp_servers.manual-only-server]',
    'command = "manual-cmd"',
    '',
    MANAGED_BLOCK_START,
    '# Auto-generated by scripts/sync-claude-all-to-codex.js',
    MANAGED_BLOCK_END,
    ''
  ].join('\n');

  const newServers = {
    'synced-server': { command: 'synced-cmd' }
  };

  const { blockText } = buildManagedMcpBlock(newServers);
  const result = applyManagedBlock(existingConfig, blockText);

  // manual-only-server should still be there (not managed)
  assert.match(result, /\[mcp_servers\.manual-only-server\]/);
  assert.match(result, /command = "manual-cmd"/);

  // synced-server should be in the managed block
  assert.match(result, /\[mcp_servers\.synced-server\]/);
});

test('applyManagedBlock handles config with no prior managed block and duplicates', () => {
  const existingConfig = [
    'model = "gpt-5.3-codex"',
    '',
    '[mcp_servers.my-server]',
    'command = "old-cmd"',
    ''
  ].join('\n');

  const newServers = {
    'my-server': { command: 'new-cmd' }
  };

  const { blockText } = buildManagedMcpBlock(newServers);
  const result = applyManagedBlock(existingConfig, blockText);

  const serverMatches = result.match(/\[mcp_servers\.my-server\]/g) || [];
  assert.equal(serverMatches.length, 1, 'my-server should appear exactly once');
  assert.match(result, /command = "new-cmd"/, 'should use the managed version');
});

test('stripDuplicateMcpEntries only strips entries for specified server names', () => {
  const config = [
    '[mcp_servers.keep-me]',
    'command = "keep"',
    '',
    '[mcp_servers.remove-me]',
    'command = "remove"',
    '',
    MANAGED_BLOCK_START,
    MANAGED_BLOCK_END,
    ''
  ].join('\n');

  const result = stripDuplicateMcpEntries(config, ['remove-me']);

  assert.match(result, /\[mcp_servers\.keep-me\]/);
  // Outside the managed block, remove-me should be gone
  const managed = extractManagedBlock(result);
  const outside = result.slice(0, managed.start) + result.slice(managed.end);
  assert.ok(!outside.includes('[mcp_servers.remove-me]'));
});
